use_frameworks!

platform :ios, '10.0'

target 'sdk-pod_Example' do
  pod 'sdk-pod', :path => '../'

  target 'sdk-pod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
